CREATE DATABASE restaurante;
USE restaurante;

CREATE TABLE banner (
id INT PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(255) NOT NULL,
descripcion VARCHAR(255) NOT NULL,
link VARCHAR(255) NOT NULL
);

CREATE TABLE colaboradores (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
descripcion VARCHAR(255) NOT NULL,
facebook VARCHAR(255) NOT NULL,
instagram VARCHAR(255) NOT NULL,
youtube VARCHAR(255) NOT NULL,
foto VARCHAR(255) NOT NULL
);

CREATE TABLE mensaje (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
correo VARCHAR(255) NOT NULL,
mensaje VARCHAR(255) NOT NULL
);

CREATE TABLE menu (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
ingredientes VARCHAR(255) NOT NULL,
precio VARCHAR(255) NOT NULL,
foto VARCHAR(255) NOT NULL
);

CREATE TABLE testimonios (
id INT PRIMARY KEY AUTO_INCREMENT,
opinion VARCHAR(255) NOT NULL,
nombre VARCHAR(255) NOT NULL
);

CREATE TABLE usuario (
id INT PRIMARY KEY AUTO_INCREMENT,
nombreUsuario VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
correo VARCHAR(255) NOT NULL
);

/*USUARIO*/
INSERT INTO usuario (nombreUsuario, password, correo) 
VALUES ('Laura123', '1234', 'laura@gmail.com');